### ISSUE TITLE
How to get CPU and GPU temperate data? 

### ISSUE THREAD

**Issue by Ahmed-Mohiuddin-Shah** [bebump/coolth#1] opened 2021-06-04 15:55 UTC
![Capture](https://user-images.githubusercontent.com/83568426/120828914-84d07980-c576-11eb-8339-798efec82c98.PNG)
The CPU and GPU temperature are not showing in the program,
Is there any solution to this?
I have three fans attached to an Arduino Nano.

**Comment by bebump** [comment] 2021-06-04 18:02
Hi Ahmed, I'll do my best to help you, but I'll need more information.

1. Please show me the contents of the log. Click the Log button, like below.
![coolth_log](https://user-images.githubusercontent.com/56175659/120844500-c01b7a00-c56f-11eb-94e8-edd4e5d6a106.png)
2. Did you build the software yourself, or did you install the release?

In any case, please go to

`C:\Users\[YOUR_USERNAME]\AppData\Local\Programs\Bebump Coolth`

and check if you can see the file `temperature_reader.exe`. Double click and run it manually, and tell me what the output is.

**Comment by Ahmed-Mohiuddin-Shah** [comment] 2021-06-04 19:39
![Capture1](https://user-images.githubusercontent.com/83568426/120854230-4ea2f200-c596-11eb-8bb7-2e3b51f11022.PNG)
![Capture2](https://user-images.githubusercontent.com/83568426/120854238-519de280-c596-11eb-9a4a-8b2fce66342a.PNG)

[edit]
I installed the release.
I don`t know how to build the software.

**Comment by bebump** [comment] 2021-06-06 11:35
Thanks for the info.

### New release for seeing at least GPU temps

I have created a new release 0.9.6 which will display and utilize your GPU temperature even if the CPU temperature cannot be read. You can use this to automate your fans based at least on your GPU temperature.

### Further investigation

The root cause of your problem is that `temperature_reader.exe` is unable to read your CPU's temperature. This could be because OpenHardwareMonitor, which is used under the hood, is unable to read the CPU temp.

What CPU model do you have?

You could also verify that this is truly the case by downloading and running Open Hardware Monitor on your machine, and sending me a screenshot like the first image on the following page.

https://openhardwaremonitor.org/

Bebump Coolth already comes with the latest released version of Open Hardware Monitor, so if you have an Intel 11 series CPU that could be a problem. But seeing the screenshot, maybe I can find a workaround or maybe switch to Libre Hardware Monitor.

**Comment by Ahmed-Mohiuddin-Shah** [comment] 2021-06-06 11:57
![Capture3](https://user-images.githubusercontent.com/83568426/120923361-9a18e580-c6e7-11eb-9fba-1d0507473afb.PNG)
The software is reading the GPU temperature correctly now.
Only CPU temp is not being shown now.
I have installed and opened Open Hardware Monitor and it is detecting CPU Temperature correctly.
My System specs:
core i5 650
nvidia gtx 650
8gb ram
hp oem system

What else could be the problem?
Thanks for the quick responses.

[Edit]
The temperature is also now changing according to GPU temperature.

**Comment by bebump** [comment] 2021-06-06 12:20
The screenshot was helpful. I can see you have reported CPU core temperatures, just not a CPU package temperature.

I released a new version (0.9.7) which will use the CPU Core 1 temperature in case there is no package temperature.

**Comment by Ahmed-Mohiuddin-Shah** [comment] 2021-06-06 18:44
![Capture 4](https://user-images.githubusercontent.com/83568426/120936397-f3513b00-c720-11eb-809c-5d7a850e0765.PNG)

It is now reading the temperature of the CPU but the CPU reading gets stuck at the reading it started with.
Rest of the program is working correctly.

Sorry for late response I was out for work.

**Comment by bebump** [comment] 2021-06-06 19:26
Thank you for the feedback. I can see the issue, and hopefully I fixed it with release 0.9.8.

**Comment by Ahmed-Mohiuddin-Shah** [comment] 2021-06-06 19:35
.exe file is not available in 0.9.8 release

**Comment by bebump** [comment] 2021-06-06 19:43
The number of things that can go wrong. I added the file.

**Comment by Ahmed-Mohiuddin-Shah** [comment] 2021-06-06 20:19
1.   ![Capture 5](https://user-images.githubusercontent.com/83568426/120938069-8347b280-c72a-11eb-814c-53e8afff82a1.PNG)
Yes! It is working now.
Thank you for helping me.

2.  If in the future if I have any issue should I post in this thread or start new issue? 

3.  I like your software. It is very simple and easy to use. You should upload some videos of your software on YouTube. I am sure people will like it. I am making a PowerMac g5 mod case and I will be uploading videos of it so I will make sure to guide people towards your program. Developers like you should be given more recognition.

4. Just one more question is it possible to add HDD0 and HDD1?

**Comment by bebump** [comment] 2021-06-07 20:50
Thank you for the kind words. I'll be closing this issue, please open a new one for future, unrelated issues.

I'll keep the HDD0 feature request in mind, although I can't promise when I might be getting around to implementing it.

**Closed as completed by bebump** 2021-06-07 20:50 UTC

**Comment by UMCURA** [comment] 2023-07-29 23:02
Hello, I have problems with the temperature of the GPU, it appears from time to time, but most of the time it does not appear in the program and the operation is wrong. I only have a fan connected, I'm testing it. I have tested the 4 versions and the same problem. What could be happening?. Thank you so much.

![FAULT](https://github.com/bebump/coolth/assets/117018370/2330241d-dbf6-407a-8034-eb3345e26632)
